PROGRAM=ImuDev

include ../../topheader.mk
include $(TOPDIR)xclass/xclass.mk
include $(TOPDIR)examples/examples.mk

PROGRAM_SOURCES += $(PROGRAM)BuildScene.cpp \
	graph.cpp \
	MadgwickAHRS/MadgwickAHRS.c \


include $(TOPDIR)/topfooter.mk
