PROGRAM=OpenCVTest

include ../../topheader.mk
include $(TOPDIR)/xclass/xclass.mk
include $(TOPDIR)/examples/examples.mk

PROGRAM_SOURCES += $(PROGRAM)BuildScene.cpp

LIBS+=-lopencv_core \
	-lopencv_videoio\
	-lopencv_imgcodecs\
	-lopencv_imgproc

include $(TOPDIR)/topfooter.mk
