PROGRAM=MqttDev

include ../../topheader.mk
include $(TOPDIR)xclass/xclass.mk
include $(TOPDIR)examples/examples.mk

PROGRAM_SOURCES += $(PROGRAM)BuildScene.cpp

LIBS += -lssl -lcrypto

include $(TOPDIR)/topfooter.mk
