PROGRAM=MidiDev

include ../../topheader.mk
include $(TOPDIR)xclass/xclass.mk
include $(TOPDIR)examples/examples.mk

PROGRAM_SOURCES += $(PROGRAM)BuildScene.cpp xmidi-linux.cpp

LIBS += -lasound

include $(TOPDIR)/topfooter.mk
