PROGRAM=OpenALTest

include ../../topheader.mk
include $(TOPDIR)/xclass/xclass.mk
include $(TOPDIR)/examples/examples.mk

PROGRAM_SOURCES += $(PROGRAM)BuildScene.cpp 

LIBS += -lopenal

include $(TOPDIR)/topfooter.mk
