PROGRAM=ComputeShaderTest

include ../../topheader.mk
include $(TOPDIR)/xclass/xclass.mk
include $(TOPDIR)/examples/examples.mk

CXXFLAGS +=-DOPENGL_MAJOR_VERSION=4 -DOPENGL_MINOR_VERSION=3

PROGRAM_SOURCES += $(PROGRAM)BuildScene.cpp 

include $(TOPDIR)/topfooter.mk
